//
//  crypto.cpp
//  pingamated
//
//  Created by Ali Mahouk on 12/24/16.
//  Copyright © 2016 Ali Mahouk. All rights reserved.
//

#include "crypto.hpp"

#include <openssl/err.h>
#include <openssl/ssl.h>

void pingamate::crypto::cleanup(void)
{
        CRYPTO_cleanup_all_ex_data();
        ERR_free_strings();
        EVP_cleanup();
}

/**
 * Prints out all the errors generated by OpenSSL.
 */
void pingamate::crypto::error(void)
{
        ERR_print_errors_fp(stderr);
}

/**
 * Initialises the OpenSSL library.
 */
void pingamate::crypto::init(void)
{
        if ( SSL_library_init() ) {
                OpenSSL_add_all_ciphers();
                OpenSSL_add_all_digests();
        } else {
                exit(EXIT_FAILURE);
        }
}
